#!/bin/sh

# Stop and disable routing services
for i in firewall dnsmasq odhcpd; do
  if [ -x /etc/init.d/"$i" ]; then
    /etc/init.d/"$i" disable
    /etc/init.d/"$i" stop
  fi
done

# Bridge Setup: Add WAN port into LAN bridge
# On RAX3000Q, eth0 is typically WAN, while eth1 is LAN ports.
# We convert LAN to DHCP client and add eth0 to its interface list.
BRLANSEC=$(uci show network | grep "\.name='br-lan'" | cut -d'.' -f2)
uci del network.${BRLANSEC}.ports
uci add_list network.${BRLANSEC}.ports='eth0'
uci add_list network.${BRLANSEC}.ports='eth1'
uci set network.${BRLANSEC}.stp='1'
uci set network.${BRLANSEC}.ipv6='0'

uci set network.lan.proto='dhcp'
uci delete network.lan.ipaddr
uci delete network.lan.netmask
uci del network.lan.ip6assign

# Remove WAN logical interfaces (Physical ports stay in bridge)
uci delete network.wan
uci delete network.wan6

# Wi-Fi Setup - Enhanced Detection
# Iterates through all wireless interfaces to apply settings broadly.
uci show wireless | grep "=wifi-iface" | cut -d'.' -f2 | cut -d'=' -f1 | while read section; do
  uci set wireless."$section".ssid='XX'
  uci set wireless."$section".encryption='psk2+ccmp'
  uci set wireless."$section".key='12345678'
  uci set wireless."$section".ieee80211r='1'
  uci set wireless."$section".mobility_domain='123f'
  uci set wireless."$section".ft_psk_generate_local='1'
  uci set wireless."$section".ft_over_ds='0'
  uci set wireless."$section".reassociation_deadline='2000'
done

# Enable all radios
uci show wireless | grep "=wifi-device" | cut -d'.' -f2 | cut -d'=' -f1 | while read radio; do
  uci set wireless."$radio".disabled='0'
done

# System/Hostname & Timezone (Cambodia)
uci set system.@system[0].hostname='XX.3000QY.ap'
uci set system.@system[0].zonename='Asia/Phnom Penh'
uci set system.@system[0].timezone='<+07>-7'

# Clean up DHCP/IPv6 RA services on LAN
if uci get dhcp.lan >/dev/null 2>&1; then
  uci del dhcp.lan.ra
  uci del dhcp.lan.ra_slaac
  uci del dhcp.lan.ra_flags
  uci del dhcp.lan.dhcpv6
fi

# Custom Switch / VLAN Configuration
# Using indices instead of anonymous IDs (cfgXXXX) for build portability.
uci set network.@switch_vlan[0].ports='6 2 4 5 1'
uci set network.@switch_vlan[0].vid='1'
uci set network.@switch_vlan[1].ports='3t 1t'
uci set network.@switch_vlan[1].vid='123'

uci add network switch_vlan
uci set network.@switch_vlan[-1].device='switch1'
uci set network.@switch_vlan[-1].vlan='3'
uci set network.@switch_vlan[-1].ports='3t 1t'
uci set network.@switch_vlan[-1].vid='234'

uci commit network
uci commit wireless
uci commit system
uci commit dhcp

# Deactivate firewall config file
[ -f /etc/config/firewall ] && mv /etc/config/firewall /etc/config/firewall.unused

exit 0

